requires 'File::Which';
requires 'Git::Repository';
requires 'Git::Repository::FileHistory', '0.03';
requires 'HTTP::Date';
requires 'List::UtilsBy';
requires 'Object::Container';
requires 'Mouse';
requires 'Path::Tiny';
requires 'Puncheur::Lite';
requires 'String::CamelCase';
requires 'Text::Markdown::Discount';
requires 'Text::Markup::Any';
requires 'Text::Xslate';
requires 'URI';
requires 'URI::tag';
requires 'XML::FeedPP';
requires 'YAML::Tiny';
