name: test
on:
  push:
    branches:
    - "**"
  pull_request: {}
jobs:
  list:
    name: List Perl Versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - uses: shogo82148/actions-setup-perl@b61fd6db748050f91bedd4d72ad5e404b5177cc0 # v1.44.1
    - name: list available perl versions
      id: set-matrix
      shell: perl {0}
      run: |
        use Actions::Core;
        my ($latest, $prev) = perl_versions();
        set_output(perl => [$latest, $prev]);
    outputs:
      perl: ${{ steps.set-matrix.outputs.perl }}
  test:
    name: Run Test with Perl ${{ matrix.perl }}
    needs: list
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        perl: ${{fromJson(needs.list.outputs.perl)}}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@b61fd6db748050f91bedd4d72ad5e404b5177cc0 # v1.44.1
      with:
        perl-version: ${{ matrix.perl }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cpanm -n Devel::Cover::Report::Coveralls
        cpanm --quiet --installdeps --notest --with-recommends .
        perl Build.PL && ./Build build && ./Build test
        RIJI_TEST_INTERNAL=1 cover -test -report coveralls
